import Head from "next/head";

import { SectionHome } from "@/components/SectionHome";
import { SectionInfo } from "@/components/SectionInfo";
import { SectionPrograms } from "@/components/SectionPrograms";
import { SectionContact } from "@/components/SectionContact";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sarah Soares</title>
        <meta
          name="Atendimento presencial e consultoria online, atendimento em Teresina, PI, residencial e personal trainer online."
          content="Generated by create next app"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.svg" />
      </Head>
      <main>
        <SectionHome />
        <SectionInfo />
        <SectionPrograms />
        <SectionContact />
      </main>
    </>
  );
}
